import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Button from '@/components/Buttons'
import Footer from '@/components/Footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Instagram Login Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/instalogo.ico" />
      </Head>
      <header>

      </header>
      <main className={`${styles.main}`}>
      <div className={styles.loginContainer}>
        <div className={styles.logo}>
        <Image src={'/images/logo.png'} alt="instagram" width={200} height={50} />
         </div>
         <form className={styles.loginForm}>
        <input type="text" placeholder="Phone number, username, or email" />
        <input type="password" placeholder="Password" />
        </form>
        
        <Button/>
         
          <div className={styles.divider}>
            
             <span className={styles.span}>OR</span>
              <hr /> 
            </div>
            <div  className={styles.facebook}>
            <Image src={'/images/facebooklogo.png'} alt="facebook login" width={170} height={23} />
           </div>
          <a href="" className={styles.forgotPassword}>Forgot password?</a>
          
          </div>
          <div className={styles.secondContainer}>
            <p className={styles.accountText}>Don't have an account?</p> <a href="" className={styles.signUp}>Sign up</a>
            </div>
            <div className={styles.bottom}>
              <p>Get the app.</p>
              <Image src={'/images/appstore.png'} alt="app store and google play buttons" width={280} height={45} />
            </div>
      </main>
      <Footer/>
    </>
  )
}
